import { useEffect } from "react";
import Head from "next/head";
import { themeChange } from "theme-change";
// components
import Layout from "./layout";
import Button from "./button";
import ThemeSelector from "./theme-selector";

export default function Home() {
  useEffect(() => {
    themeChange(false);
  });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <ThemeSelector />
        <div className="divider">OR</div>
        <Button />
        <div className="divider">OR</div>
        Press <kbd className="kbd kbd-sm">F</kbd> to pay respects!!
        <div className="divider">OR</div>
      </Layout>
    </div>
  );
}
